run_settings:
  device: cuda

wandb:
  keep_top_runs: 10

train_loader:
  batch_size: 256
  shuffle: true
  num_workers: 4
  prefetch_factor: 8
  persistent_workers: true

val_loader:
  batch_size: 256
  shuffle: false
  num_workers: 4
  prefetch_factor: 8
  persistent_workers: true

profile_training: false

train_eval:
  top_k: [ 10 ]
  metrics: [ 'ndcg', 'recall' ]
  calculate_std: false