base_configs:
  - './../base_settings.yml'
  - './../dataloader_conf.yml'

learn:
  n_epochs: 50
  lr: 0.0008878328740862263
  wd: 0.001964405699868246
  optimizer: 'adamw'
  optimizing_metric: 'ndcg@10'
  rec_loss: 'bpr'
  loss_aggregator: 'mean'
  max_patience: 5

dataset:
  n_negative_samples: 10

model:
  embedding_dim: 500
  use_user_bias: false
  use_item_bias: false
  use_global_bias: false