base_configs:
  - './../base_settings.yml'
  - './../dataloader_conf.yml'
  - './../dataset_onion18_conf.yml'
  - './../train_eval_conf.yml'

run_settings:
  seed: 42
  device: cuda
  batch_verbose: true

wandb:
  use_wandb: true

learn:
  n_epochs: 50
  lr: 5e-5
  wd: 1e-3
  optimizer: 'adamw'
  optimizing_metric: 'ndcg@10'
  rec_loss: 'bpr'
  loss_aggregator: 'mean'
  max_patience: 5

dataset:
  n_negative_samples: 10
  model_requires_train_interactions: true
  model_requires_item_interactions: true

model:
  shared_common_dim: 128

  user:
    embedding_dim: -1
    feature_name: 'user_embedding'
    activation_fn: 'relu'

  item:
    embedding_dim: -1
    feature_name: 'item_embedding'
    activation_fn: 'relu'
