base_configs:
  - './../base_settings.yml'
  - './../dataloader_conf.yml'
  - './../dataset_ml1m_conf.yml'
  - './../train_eval_conf.yml'

learn:
  n_epochs: 50
  lr: 5e-5
  wd: 1e-3
  optimizer: 'adamw'
  optimizing_metric: 'ndcg@10'
  rec_loss: 'bpr'
  loss_aggregator: 'mean'
  max_patience: 5

dataset:
  n_negative_samples: 10
  model_requires_train_interactions: true
  model_requires_item_interactions: true

model:
  shared_common_dim: 256

  user:
    single_branch_hidden_layers: [ 512 ]
    preference_hidden_layers: [ ]
    common_modality_dim: 512
    activation_fn: 'relu'
    single_branch_input_dropout: 2e-2
    normalize_single_branch_input: true

    aggregation_fn: 'mean'
    embedding_regularization_type: 'pairwise_single'
    central_modality: 'interactions'

    train_modalities: [ 'interactions', 'gender' ]

    apply_output_activation: true
    apply_batch_normalization: true
    apply_batch_norm_every: 2

    features:
      - feature_name: 'interactions'
        feature_hidden_layers: [ ]
      - feature_name: 'age'
        feature_hidden_layers: [ ]
      - feature_name: 'gender'
        feature_hidden_layers: [ ]
      - feature_name: 'occupation'
        feature_hidden_layers: [ ]

  item:
    embedding_dim: -1
    feature_name: 'interactions'
    activation_fn: 'relu'
