base_configs:
  - './../base_settings.yml'
  - './../dataloader_conf.yml'
  - './../dataset_ml1m_conf.yml'

learn:
  n_epochs: 40
  lr: 1e-3
  wd: 1e-6
  optimizer: 'adamw'
  optimizing_metric: 'ndcg@10'
  rec_loss: 'bpr'
  loss_aggregator: 'mean'
  max_patience: 5

dataset:
  n_negative_samples: 10

model:
  # parameters for base mf
  embedding_dim: 64
  use_user_bias: true
  use_item_bias: false
  use_global_bias: false

  # parameters for user feature extension
  aggregate_for_rec: true  # functions as activation switch
  feature_name: 'gender'
  lambda_content: 0.0001
  temperature: 0.1
  embedding_loss_aggregator: 'mean'
  intermediate_layers: ~
